### ISSUE TITLE
用户掉落反馈系统

### ISSUE THREAD

**Issue by ccxcxd** [ccxcxd/GFDB-Web#18]
掉落数据现在已经无法通过拆包获得，只能人工统计。是否考虑添加一个用户反馈系统

因为这会使网站从静态变成动态，需要添加后台数据库，是个很大的补丁

**Comment by ccxcxd** [comment]
随机但有规律的初始状况（类似8-4N），也是反馈系统的潜在用户

**Comment by Runtu4378** [comment]
还要考虑到数据的可靠性

**Comment by ccxcxd** [comment]
因为之前的更新，掉落信息已经是标准UI的一部分了，可以拆包了，所以不需要再做了
